---
apiVersion: core.akuity.io/v1alpha1
kind: NamespaceClass
metadata:
  name: foo
spec:
  inheritedResources:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: foo-config
      template:
        data:
          key1: "valueNEWNEWNEW"
          key2: "valueNEWNEWNEW"
          environment: "production"
    
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: foo-viewer-role
      template:
        rules:
        - apiGroups: [""]
          resources: ["pods", "services"]
          verbs: ["get", "list", "watch"]
    
     #Simple busybox pod
    - apiVersion: v1
      kind: Pod
      metadata:
        name: foo-busybox
      template:
        spec:
          containers:
          - name: busybox
            image: busybox:latest
            command: ["sleep", "3600"]
            resources:
              limits:
                memory: "64Mi"
                cpu: "100m"

---
# NamespaceClass "bar"
apiVersion: core.akuity.io/v1alpha1
kind: NamespaceClass
metadata:
  name: bar
spec:
  inheritedResources:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: bar-config
      template:
        data:
          app: "bar-application"
          environment: "development"
          log-level: "debug"
    
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: bar-admin-role
      template:
        rules:
        - apiGroups: ["apps"]
          resources: ["deployments", "statefulsets"]
          verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
    
    - apiVersion: v1
      kind: Secret
      metadata:
        name: bar-credentials
      template:
        type: Opaque
        data:
          username: YWRtaW4=  # admin in base64
          password: cGFzc3dvcmQxMjM=  # password123 in base64

---
# Namespace referring to "foo" class
apiVersion: v1
kind: Namespace
metadata:
  name: testfoo
  labels:
    namespaceclass.akuity.io/name: foo

---
# Namespace referring to "bar" class
apiVersion: v1
kind: Namespace
metadata:
  name: testbar
  labels:
    namespaceclass.akuity.io/name: bar
